//! zkCred — On-Chain Groth16 Verifier (Soroban Smart Contract)
//!
//! This contract lives on the Stellar network (Testnet → Mainnet) and serves
//! as the *single source of truth* for proof verification.
//!
//! ## Curve choice — BLS12-381 (the refit)
//!
//! Stellar's released protocol exposes **BLS12-381** cryptographic host
//! functions (`env.crypto().bls12_381()`), NOT BN254. The proving pipeline is
//! therefore arkworks `ark-groth16` over `ark-bls12-381`, which emits proofs
//! and a verification key in the BLS12-381 groups. All three layers — circuit,
//! prover, and this verifier — now speak the same cryptographic language.
//!
//! ## What it does
//! 1. Stores the Groth16 Verification Key (VK) generated by the trusted setup.
//! 2. Exposes `verify_proof()`, which uses BLS12-381 host functions to run an
//!    on-chain pairing check.
//! 3. Returns `true` iff the proof is valid AND the nonce is fresh.
//!
//! ## Groth16 Verification Equation
//!
//!   e(A, B) == e(α, β) · e(vk_x, γ) · e(C, δ)
//!
//! Re-arranged into product-of-pairings-equals-one form (what `pairing_check`
//! evaluates):
//!
//!   e(A, B) · e(−α, β) · e(−vk_x, γ) · e(−C, δ) == 1
//!
//! Where `vk_x = IC[0] + threshold·IC[1] + asset_id·IC[2] + nonce·IC[3]`.
//!
//! ## Serialization (must match the arkworks adapter in the prover)
//!   G1 point  = 96 bytes  : be(x) || be(y),   each Fp is 48 BE bytes
//!   G2 point  = 192 bytes : be(x_c1)||be(x_c0)||be(y_c1)||be(y_c0)
//!   Scalar Fr = 32 bytes  : big-endian, reduced mod r
//!   Infinity  = all-zero bytes

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    crypto::bls12_381::{Fr, G1Affine, G2Affine},
    Address, BytesN, Env, Vec,
};

// BLS12-381 base field modulus p, big-endian, 48 bytes.
// p = 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f624
//       1eabfffeb153ffffb9feffffffffaaab
const BLS12_381_FP_MODULUS_BE: [u8; 48] = [
    0x1a, 0x01, 0x11, 0xea, 0x39, 0x7f, 0xe6, 0x9a, 0x4b, 0x1b, 0xa7, 0xb6, 0x43, 0x4b, 0xac, 0xd7,
    0x64, 0x77, 0x4b, 0x84, 0xf3, 0x85, 0x12, 0xbf, 0x67, 0x30, 0xd2, 0xa0, 0xf6, 0xb0, 0xf6, 0x24,
    0x1e, 0xab, 0xff, 0xfe, 0xb1, 0x53, 0xff, 0xff, 0xb9, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xaa, 0xab,
];

// ─────────────────────────────────────────────────────────────────────────────
// Data Types
// ─────────────────────────────────────────────────────────────────────────────

/// Groth16 Verification Key produced by the trusted setup (arkworks).
///
/// Byte sizes follow the BLS12-381 uncompressed encoding documented above.
/// Set once at deployment via `initialize()`.
#[contracttype]
#[derive(Clone)]
pub struct VerificationKey {
    /// [α]_1 — Alpha point on G1 (96 bytes)
    pub alpha_g1: BytesN<96>,
    /// [β]_2 — Beta point on G2 (192 bytes)
    pub beta_g2: BytesN<192>,
    /// [γ]_2 — Gamma point on G2 (192 bytes)
    pub gamma_g2: BytesN<192>,
    /// [δ]_2 — Delta point on G2 (192 bytes)
    pub delta_g2: BytesN<192>,
    /// Input Commitments [IC_0, IC_1, IC_2, IC_3], each a G1 point (96 bytes):
    ///   IC_0 — constant term
    ///   IC_1 — coefficient for `threshold`
    ///   IC_2 — coefficient for `asset_id`
    ///   IC_3 — coefficient for `nonce`
    pub ic: Vec<BytesN<96>>,
}

/// A Groth16 proof (π) over BLS12-381.
#[contracttype]
#[derive(Clone)]
pub struct Proof {
    /// π_A ∈ G1 (96 bytes)
    pub a: BytesN<96>,
    /// π_B ∈ G2 (192 bytes)
    pub b: BytesN<192>,
    /// π_C ∈ G1 (96 bytes)
    pub c: BytesN<96>,
}

/// Public inputs bound to the proof. Each is a 32-byte big-endian Fr scalar.
#[contracttype]
#[derive(Clone)]
pub struct PublicInputs {
    /// Minimum balance threshold (e.g. $5,000 USDC = 5_000_000_000)
    pub threshold: BytesN<32>,
    /// Asset identifier — field-element hash of the asset code (e.g. "USDC")
    pub asset_id: BytesN<32>,
    /// Unique random nonce — prevents the same proof from being accepted twice
    pub nonce: BytesN<32>,
}

/// Contract storage keys.
#[contracttype]
pub enum StorageKey {
    Admin,
    VerificationKey,
    /// Tracks which nonces have already been used (replay protection)
    UsedNonce(BytesN<32>),
}

// ─────────────────────────────────────────────────────────────────────────────
// Contract
// ─────────────────────────────────────────────────────────────────────────────

#[contract]
pub struct ZkCredVerifier;

#[contractimpl]
impl ZkCredVerifier {
    // ── Admin Functions ───────────────────────────────────────────────────────

    /// Initialize the contract with the Verification Key from the trusted setup.
    /// Call once immediately after deployment.
    pub fn initialize(env: Env, admin: Address, vk: VerificationKey) {
        if env.storage().instance().has(&StorageKey::Admin) {
            panic!("Contract is already initialized");
        }
        admin.require_auth();
        if vk.ic.len() != 4 {
            panic!("VK must contain exactly 4 IC points (1 constant + 3 public inputs)");
        }
        env.storage().instance().set(&StorageKey::Admin, &admin);
        env.storage()
            .instance()
            .set(&StorageKey::VerificationKey, &vk);
        env.storage().instance().extend_ttl(100_000, 100_000);
    }

    /// Replace the Verification Key. Admin-only. Required if the circuit changes.
    pub fn update_vk(env: Env, vk: VerificationKey) {
        let admin: Address = env
            .storage()
            .instance()
            .get(&StorageKey::Admin)
            .expect("Not initialized");
        admin.require_auth();
        if vk.ic.len() != 4 {
            panic!("VK must contain exactly 4 IC points");
        }
        env.storage()
            .instance()
            .set(&StorageKey::VerificationKey, &vk);
    }

    // ── Core Verification Function ────────────────────────────────────────────

    /// Verify a zkCred zero-knowledge proof on-chain via BLS12-381 host
    /// functions. Returns `true` iff the proof is valid for the given public
    /// inputs AND the nonce has not been previously consumed.
    pub fn verify_proof(env: Env, proof: Proof, inputs: PublicInputs) -> bool {
        // ── Step 0: Replay protection ─────────────────────────────────────────
        let nonce_key = StorageKey::UsedNonce(inputs.nonce.clone());
        if env.storage().temporary().has(&nonce_key) {
            return false; // Proof already consumed
        }

        let vk: VerificationKey = env
            .storage()
            .instance()
            .get(&StorageKey::VerificationKey)
            .expect("Call initialize() before verify_proof()");

        let bls = env.crypto().bls12_381();

        // ── Step 1: Prepared public input vk_x ────────────────────────────────
        //
        //   vk_x = IC[0] + threshold·IC[1] + asset_id·IC[2] + nonce·IC[3]
        //
        // Computed as an MSM over the three variable IC points, then added to
        // the constant term IC[0].
        let ic0 = G1Affine::from_bytes(vk.ic.get(0).unwrap());
        let ic1 = G1Affine::from_bytes(vk.ic.get(1).unwrap());
        let ic2 = G1Affine::from_bytes(vk.ic.get(2).unwrap());
        let ic3 = G1Affine::from_bytes(vk.ic.get(3).unwrap());

        let mut msm_points: Vec<G1Affine> = Vec::new(&env);
        msm_points.push_back(ic1);
        msm_points.push_back(ic2);
        msm_points.push_back(ic3);

        let mut msm_scalars: Vec<Fr> = Vec::new(&env);
        msm_scalars.push_back(Fr::from_bytes(inputs.threshold));
        msm_scalars.push_back(Fr::from_bytes(inputs.asset_id));
        msm_scalars.push_back(Fr::from_bytes(inputs.nonce));

        let acc = bls.g1_msm(msm_points, msm_scalars);
        let vk_x = bls.g1_add(&ic0, &acc);

        // ── Step 2: Groth16 pairing check ─────────────────────────────────────
        //
        //   e(A, B) · e(−α, β) · e(−vk_x, γ) · e(−C, δ) == 1
        let a = G1Affine::from_bytes(proof.a);
        let c = G1Affine::from_bytes(proof.c);

        let neg_alpha = negate_g1(&env, &vk.alpha_g1);
        let neg_vk_x = negate_g1(&env, &vk_x.to_bytes());
        let neg_c = negate_g1(&env, &c.to_bytes());

        let mut vp1: Vec<G1Affine> = Vec::new(&env);
        vp1.push_back(a); //  A
        vp1.push_back(neg_alpha); // −α
        vp1.push_back(neg_vk_x); // −vk_x
        vp1.push_back(neg_c); // −C

        let mut vp2: Vec<G2Affine> = Vec::new(&env);
        vp2.push_back(G2Affine::from_bytes(proof.b)); //  B
        vp2.push_back(G2Affine::from_bytes(vk.beta_g2)); //  β
        vp2.push_back(G2Affine::from_bytes(vk.gamma_g2)); //  γ
        vp2.push_back(G2Affine::from_bytes(vk.delta_g2)); //  δ

        let is_valid = bls.pairing_check(vp1, vp2);

        // ── Step 3: Record nonce to block replay ──────────────────────────────
        if is_valid {
            // TTL ≈ 150 days at 5s/ledger
            env.storage().temporary().set(&nonce_key, &true);
            env.storage()
                .temporary()
                .extend_ttl(&nonce_key, 2_592_000, 2_592_000);
        }

        is_valid
    }

    // ── Read-Only Functions ───────────────────────────────────────────────────

    pub fn get_vk(env: Env) -> VerificationKey {
        env.storage()
            .instance()
            .get(&StorageKey::VerificationKey)
            .expect("Not initialized")
    }

    pub fn get_admin(env: Env) -> Address {
        env.storage()
            .instance()
            .get(&StorageKey::Admin)
            .expect("Not initialized")
    }

    pub fn is_nonce_used(env: Env, nonce: BytesN<32>) -> bool {
        env.storage()
            .temporary()
            .has(&StorageKey::UsedNonce(nonce))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Negate a BLS12-381 G1 point: (x, y) → (x, p − y).
///
/// G1 is 96 bytes: be(x)[0..48] || be(y)[48..96]. The point at infinity is
/// encoded as all-zero bytes and negates to itself.
fn negate_g1(env: &Env, point: &BytesN<96>) -> G1Affine {
    let p = point.to_array();

    // Point at infinity (all zero) negates to itself.
    let mut all_zero = true;
    for b in p.iter() {
        if *b != 0 {
            all_zero = false;
            break;
        }
    }
    if all_zero {
        return G1Affine::from_bytes(BytesN::from_array(env, &p));
    }

    let mut x = [0u8; 48];
    let mut y = [0u8; 48];
    x.copy_from_slice(&p[0..48]);
    y.copy_from_slice(&p[48..96]);

    // neg_y = p − y  (big-endian subtraction, 0 <= y < p)
    let neg_y = be_sub_48(&BLS12_381_FP_MODULUS_BE, &y);

    let mut result = [0u8; 96];
    result[0..48].copy_from_slice(&x);
    result[48..96].copy_from_slice(&neg_y);

    G1Affine::from_bytes(BytesN::from_array(env, &result))
}

/// Big-endian 48-byte subtraction: a − b (assumes a >= b).
fn be_sub_48(a: &[u8; 48], b: &[u8; 48]) -> [u8; 48] {
    let mut result = [0u8; 48];
    let mut borrow: i16 = 0;
    for i in (0..48).rev() {
        let diff = a[i] as i16 - b[i] as i16 - borrow;
        if diff < 0 {
            result[i] = (diff + 256) as u8;
            borrow = 1;
        } else {
            result[i] = diff as u8;
            borrow = 0;
        }
    }
    result
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Bytes};

    fn zeros<const N: usize>(env: &Env) -> BytesN<N> {
        BytesN::from_array(env, &[0u8; N])
    }

    fn dummy_vk(env: &Env) -> VerificationKey {
        let mut ic = Vec::new(env);
        for _ in 0..4 {
            ic.push_back(zeros::<96>(env));
        }
        VerificationKey {
            alpha_g1: zeros::<96>(env),
            beta_g2: zeros::<192>(env),
            gamma_g2: zeros::<192>(env),
            delta_g2: zeros::<192>(env),
            ic,
        }
    }

    #[test]
    fn test_initialize_and_get_vk() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register_contract(None, ZkCredVerifier);
        let client = ZkCredVerifierClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        client.initialize(&admin, &dummy_vk(&env));
        assert_eq!(client.get_admin(), admin);
        assert_eq!(client.get_vk().ic.len(), 4);
    }

    #[test]
    #[should_panic(expected = "already initialized")]
    fn test_double_initialize_panics() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register_contract(None, ZkCredVerifier);
        let client = ZkCredVerifierClient::new(&env, &contract_id);
        let admin = Address::generate(&env);
        client.initialize(&admin, &dummy_vk(&env));
        client.initialize(&admin, &dummy_vk(&env));
    }

    #[test]
    fn test_nonce_not_recorded_on_failed_proof() {
        let env = Env::default();
        env.mock_all_auths();
        let contract_id = env.register_contract(None, ZkCredVerifier);
        let client = ZkCredVerifierClient::new(&env, &contract_id);

        let admin = Address::generate(&env);
        client.initialize(&admin, &dummy_vk(&env));

        let proof = Proof {
            a: zeros::<96>(&env),
            b: zeros::<192>(&env),
            c: zeros::<96>(&env),
        };
        let nonce = BytesN::from_array(&env, &[0xAB; 32]);
        let inputs = PublicInputs {
            threshold: zeros::<32>(&env),
            asset_id: zeros::<32>(&env),
            nonce: nonce.clone(),
        };

        // All-zero (infinity) points will not satisfy the pairing equation.
        let result = client.verify_proof(&proof, &inputs);
        assert!(!result, "Dummy proof must not verify");
        assert!(!client.is_nonce_used(&nonce), "Nonce must not be recorded on failure");
    }

    #[test]
    fn test_negate_g1_infinity_is_identity() {
        let env = Env::default();
        let inf = zeros::<96>(&env);
        let neg = negate_g1(&env, &inf);
        assert_eq!(neg.to_bytes(), inf);
    }

    #[test]
    fn test_be_sub_48_basic() {
        let mut a = [0u8; 48];
        let mut b = [0u8; 48];
        a[47] = 5;
        b[47] = 3;
        let r = be_sub_48(&a, &b);
        assert_eq!(r[47], 2);
        // borrow propagation
        let mut a2 = [0u8; 48];
        a2[46] = 1; // value = 256
        let mut b2 = [0u8; 48];
        b2[47] = 1; // value = 1
        let r2 = be_sub_48(&a2, &b2); // 256 - 1 = 255
        assert_eq!(r2[47], 0xff);
        assert_eq!(r2[46], 0x00);
    }

    // Silence unused import warning when bls path is exercised only on-chain.
    #[allow(dead_code)]
    fn _bytes_marker(env: &Env) -> Bytes {
        Bytes::new(env)
    }
}
