#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Build, Deploy & Initialize the Soroban Verifier Contract
#
# What this does:
#   1. Compiles the Rust verifier contract to WASM (release)
#   2. Deploys the WASM to Stellar Testnet via the Stellar CLI
#   3. Reads Backend/prover/vk.json (generated by Step 0)
#   4. Calls initialize(admin, vk) with the real Groth16 VK bytes
#   5. Writes the new contract ID to:
#        Backend/scripts/.contract_id
#        Frontend/src/config.ts   (auto-patched)
#
# Prerequisites:
#   • Rust + wasm32-unknown-unknown target:
#       rustup target add wasm32-unknown-unknown
#   • Stellar CLI (v22+):
#       curl --proto '=https' --tlsv1.2 -sSf https://sh.stellar.org | sh
#   • A funded testnet account:
#       stellar keys generate deployer --network testnet
#       stellar keys fund deployer --network testnet
#   • Run Step 0 first to generate vk.json:
#       bash Backend/scripts/0_prover_setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$BACKEND_DIR/.." && pwd)"
CONTRACTS_DIR="$BACKEND_DIR/contracts"
PROVER_DIR="$BACKEND_DIR/prover"
FRONTEND_CONFIG="$PROJECT_ROOT/Frontend/src/config.ts"
NETWORK="testnet"
ACCOUNT="${STELLAR_ACCOUNT:-deployer}"   # Override via env: STELLAR_ACCOUNT=mykey bash 3_deploy...

VK_JSON="$PROVER_DIR/vk.json"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " zkCred — Step 3: Build, Deploy & Initialize Soroban Verifier"
echo " Network : $NETWORK   |   Account : $ACCOUNT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Preflight checks ──────────────────────────────────────────────────────────
if [[ ! -f "$VK_JSON" ]]; then
  echo ""
  echo "✗ ERROR: $VK_JSON not found."
  echo "  Run Step 0 first: bash Backend/scripts/0_prover_setup.sh"
  exit 1
fi

# Check that stellar CLI is available
if ! command -v stellar &> /dev/null; then
  echo ""
  echo "✗ ERROR: 'stellar' CLI not found."
  echo "  Install: curl --proto '=https' --tlsv1.2 -sSf https://sh.stellar.org | sh"
  exit 1
fi

echo ""
echo "✓ vk.json found."

# ── Step 3a: Compile the verifier contract to WASM ───────────────────────────
echo ""
echo "→ [1/4] Building verifier contract → WASM (release)…"
cd "$CONTRACTS_DIR"
cargo build \
  --package zkcred-verifier \
  --target wasm32-unknown-unknown \
  --release

WASM_RAW="$CONTRACTS_DIR/target/wasm32-unknown-unknown/release/zkcred_verifier.wasm"
echo "✓ WASM built: $WASM_RAW"

# ── Step 3b: Optimize WASM ────────────────────────────────────────────────────
echo ""
echo "→ [2/4] Optimizing WASM size…"
WASM_OPT="${WASM_RAW%.wasm}.optimized.wasm"
stellar contract optimize \
  --wasm "$WASM_RAW" \
  --wasm-out "$WASM_OPT"
echo "✓ Optimized WASM: $WASM_OPT"

# ── Step 3c: Deploy to testnet ────────────────────────────────────────────────
echo ""
echo "→ [3/4] Deploying to Stellar $NETWORK…"
CONTRACT_ID=$(stellar contract deploy \
  --wasm "$WASM_OPT" \
  --source "$ACCOUNT" \
  --network "$NETWORK")

echo "✓ Deployed! Contract ID: $CONTRACT_ID"
echo "$CONTRACT_ID" > "$SCRIPT_DIR/.contract_id"

# ── Step 3d: Build the VK XDR argument from vk.json ─────────────────────────
#
# The stellar CLI accepts struct arguments as JSON objects when using
# `stellar contract invoke`. We parse vk.json with jq and build the
# VerificationKey struct JSON that matches the contract's contracttype.
echo ""
echo "→ [4/4] Reading VK from $VK_JSON…"

ALPHA_G1=$(jq -r '.alpha_g1' "$VK_JSON")
BETA_G2=$(jq  -r '.beta_g2'  "$VK_JSON")
GAMMA_G2=$(jq -r '.gamma_g2' "$VK_JSON")
DELTA_G2=$(jq -r '.delta_g2' "$VK_JSON")
# IC is an array — extract each element
IC_0=$(jq -r '.ic[0]' "$VK_JSON")
IC_1=$(jq -r '.ic[1]' "$VK_JSON")
IC_2=$(jq -r '.ic[2]' "$VK_JSON")
IC_3=$(jq -r '.ic[3]' "$VK_JSON")

echo "  alpha_g1: ${ALPHA_G1:0:24}…"
echo "  IC[0..3]: ${IC_0:0:16}…"

ADMIN_ADDRESS=$(stellar keys address "$ACCOUNT")
echo ""
echo "→ Calling initialize(admin=$ADMIN_ADDRESS, vk=…) on $CONTRACT_ID …"

stellar contract invoke \
  --id     "$CONTRACT_ID" \
  --source "$ACCOUNT" \
  --network "$NETWORK" \
  -- initialize \
  --admin "$ADMIN_ADDRESS" \
  --vk "{
    \"alpha_g1\": \"$ALPHA_G1\",
    \"beta_g2\":  \"$BETA_G2\",
    \"gamma_g2\": \"$GAMMA_G2\",
    \"delta_g2\": \"$DELTA_G2\",
    \"ic\": [\"$IC_0\", \"$IC_1\", \"$IC_2\", \"$IC_3\"]
  }"

echo "✓ Contract initialized with real VK."

# ── Step 3e: Update Frontend config ───────────────────────────────────────────
echo ""
echo "→ Patching Frontend/src/config.ts with new contract ID…"

if [[ -f "$FRONTEND_CONFIG" ]]; then
  # Replace the VERIFIER_CONTRACT_ID line in-place
  sed -i "s|export const VERIFIER_CONTRACT_ID = \".*\";|export const VERIFIER_CONTRACT_ID = \"$CONTRACT_ID\";|" "$FRONTEND_CONFIG"
  echo "✓ config.ts updated."
else
  echo "  (config.ts not found — update manually)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ✓ Deployment complete!"
echo ""
echo "   Contract ID : $CONTRACT_ID"
echo "   Network     : $NETWORK"
echo "   Explorer    : https://stellar.expert/explorer/testnet/contract/$CONTRACT_ID"
echo ""
echo " NEXT: Start the frontend"
echo "   cd Frontend && npm run dev"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
